sonar.organization=robintrassard
sonar.projectKey=robintrassard_perf-sentinel
sonar.projectName=perf-sentinel

sonar.sources=crates/sentinel-core/src,crates/sentinel-cli/src
sonar.tests=crates/sentinel-core/tests,crates/sentinel-cli/tests
sonar.exclusions=**/target/**

sonar.rust.lcov.reportPaths=lcov.info
sonar.rust.clippy.reportPaths=clippy-report.json
sonar.host.url=https://sonarcloud.io
