apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "perf-sentinel.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "perf-sentinel.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  perf-sentinel.toml: |
    {{- .Values.config.toml | nindent 4 }}
