apiVersion: v1
kind: Service
metadata:
  name: {{ include "perf-sentinel.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "perf-sentinel.labels" . | nindent 4 }}
  {{- $annotations := merge (deepCopy (.Values.service.annotations | default dict)) (.Values.commonAnnotations | default dict) }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "perf-sentinel.selectorLabels" . | nindent 4 }}
  ports:
    - name: otlp-grpc
      port: {{ .Values.service.ports.otlpGrpc.port }}
      targetPort: otlp-grpc
      protocol: TCP
      {{- with .Values.service.ports.otlpGrpc.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
    - name: otlp-http
      port: {{ .Values.service.ports.otlpHttp.port }}
      targetPort: otlp-http
      protocol: TCP
      {{- with .Values.service.ports.otlpHttp.appProtocol }}
      appProtocol: {{ . }}
      {{- end }}
